  @hostname=192.168.10.218
  @port=4000
  @host={{hostname}}:{{port}}

  ###
  POST http://{{host}}/users/register HTTP/1.1
  content-type: application/json;charset=UTF-8
  
  {
      "username":"testaccount2020041101",
      "password" : "test"
  }

###
 POST http://{{host}}/users/authenticate HTTP/1.1
  content-type: application/json;charset=UTF-8
  
  {
     "username":"testaccount2020041101",
      "password" : "test"
  }

  
###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZThkZDhlZDRmZGEyZTUyZWMwMTBjNzQiLCJpYXQiOjE1ODYzOTUxMjR9.y8_4vrO46tdVU26Tty1ZduD6Dp4904mdLHe0JYQlP8k
 GET http://{{host}}/users/ HTTP/1.1
  content-type: application/json;charset=UTF-8
  Authorization: Bearer {{token}}

  
  
###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZThkZDhlZDRmZGEyZTUyZWMwMTBjNzQiLCJpYXQiOjE1ODYzOTUxMjR9.y8_4vrO46tdVU26Tty1ZduD6Dp4904mdLHe0JYQlP8k
 GET http://{{host}}/users/current HTTP/1.1
  content-type: application/json;charset=UTF-8
  Authorization: Bearer {{token}}



  
###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZThkZDhlZDRmZGEyZTUyZWMwMTBjNzQiLCJpYXQiOjE1ODYzOTUxMjR9.y8_4vrO46tdVU26Tty1ZduD6Dp4904mdLHe0JYQlP8k
 GET http://{{host}}/users/5e8dd5ef327b4a64ece62a57 HTTP/1.1
  content-type: application/json;charset=UTF-8
  Authorization: Bearer {{token}}


###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1ZThkZDhlZDRmZGEyZTUyZWMwMTBjNzQiLCJpYXQiOjE1ODYzOTUxMjR9.y8_4vrO46tdVU26Tty1ZduD6Dp4904mdLHe0JYQlP8k
 PUT http://{{host}}/users/5e8dd5ef327b4a64ece62a57 HTTP/1.1
  content-type: application/json;charset=UTF-8
  Authorization: Bearer {{token}}

  {
     "username":"testaccount998"
  }


###
 DELETE http://{{host}}/users/5e8dd8ed4fda2e52ec010c74 HTTP/1.1
  Authorization: Bearer {{token}}